eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8094
spring:
  application:
    name: service-auth
  security:
    user:
      name: william
      password: root
      roles: ADMIN,USER
security:
  oauth2:
    client: