server:
  port: 9090
spring:
  application:
    name: service-gateway
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/

zuul:
  routes:
    gateway:
      path: /login/**
      serviceId: service-gateway
    school:
      path: /school/**
      serviceId: service-school
    student:
      path: /student/**
      serviceId: service-student
  ribbon:
    eager-load:
      enabled: true