eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8100
spring:
  application:
    name: service-zuul
zuul:
  routes:
    teacher:
      path: /teacher/**
      serviceId: service-school
    subject:
      path: /subject/**
      serviceId: service-school
    student:
      path: /student/**
      serviceId: service-student