eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
server:
  port: 9090
spring:
  application:
    name: service-zuul
  security:
    user:
      name: admin
      password: root
      roles: ADMIN, USER
zuul:
  routes:
    school:
      path: /school/**
      serviceId: service-school
    student:
      path: /student/**
      serviceId: service-student