eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8100
spring:
  application:
    name: service-zuul
zuul:
  routes:
    school:
      path: /school/**
      serviceId: service-school
    student:
      path: /student/**
      serviceId: service-student
    login:
      path: /login/**
      serviceId: service-zuul