server:
  port: 9082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: springdb
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-student
  cloud:
    config:
      uri: http://localhost:9085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/

mybatis:
  config-location: classpath:springdb/mybatis-config.xml
  mapper-locations: classpath:springdb/mapper/*.xml